default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['GALAPAGOS_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['GALAPAGOS_DB_1_PORT_5432_TCP_PORT'] %>
  username: postgres
  password:

development:
  <<: *default
  database: galapagos_development

test:
  <<: *default
  database: galapagos_test

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRESQL_DATABASE']  %>
  username: <%= ENV['POSTGRESQL_USERNAME']  %>
  password: <%= ENV['POSTGRESQL_PASSWORD']  %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  pool: 20
  port: 5432
