default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['GALAPAGOS_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['GALAPAGOS_DB_1_PORT_5432_TCP_PORT'] %>
  username: postgres
  password:

development:
  <<: *default
  database: galapagos_development

test:
  <<: *default
  database: galapagos_test
